(()=>{
  const DEV_VERSION='0.2.1-dev';
  const SUPPORTED='.csv,.tsv,.txt,.xlsx,.xls,.numbers';
  function loadScript(src){return new Promise((resolve,reject)=>{if([...document.scripts].some(s=>s.src===src))return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('無法載入試算表讀取元件'));document.head.appendChild(s)})}
  async function ensureSheetJS(numbers=false){if(typeof XLSX==='undefined')await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js');if(numbers&&typeof XLSX_ZAHL_PAYLOAD==='undefined')await loadScript('https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.zahl.js')}
  function rowsToRoster(rows){rows=(rows||[]).filter(r=>Array.isArray(r)&&r.some(v=>String(v??'').trim()!==''));if(!rows.length)return[];const norm=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,'');const h=rows[0].map(norm);let id=h.findIndex(x=>['學號','studentid','student_id','id'].includes(x));let nm=h.findIndex(x=>['姓名','name','studentname','student_name'].includes(x));let start=1;if(id<0||nm<0){id=0;nm=1;start=0}return rows.slice(start).filter(r=>String(r[id]??'').trim()&&String(r[nm]??'').trim()).map((r,i)=>({student_id:String(r[id]).trim(),name:String(r[nm]).trim(),run:null,order:null,status:'pending',drawn_question:'',origIndex:i}))}
  async function acceptRoster(students,source){if(!students.length)throw new Error('找不到「學號、姓名」資料');const ids=students.map(s=>s.student_id);const dup=[...new Set(ids.filter((x,i)=>ids.indexOf(x)!==i))];if(dup.length)throw new Error('發現重複學號：'+dup.slice(0,8).join('、')+(dup.length>8?'…':''));if(state.students?.length&&!confirm(`目前已有 ${state.students.length} 位學生。要以新名單取代嗎？\n既有成績不會自動對應到新名單。`))return;state.students=students;state.rosterLocked=false;await save();renderRoster();renderRunSelectors();alert(`已從 ${source} 匯入 ${students.length} 位學生（尚未隨機排序）`)}
  async function importFile(file){if(!file)return;const ext=(file.name.split('.').pop()||'').toLowerCase();try{let students=[];if(['csv','tsv','txt'].includes(ext)){students=parseRoster(await file.text())}else if(['xlsx','xls','numbers'].includes(ext)){await ensureSheetJS(ext==='numbers');const opts={type:'array'};if(ext==='numbers'&&typeof XLSX_ZAHL_PAYLOAD!=='undefined')opts.numbers=XLSX_ZAHL_PAYLOAD;const wb=XLSX.read(await file.arrayBuffer(),opts);if(!wb.SheetNames?.length)throw new Error('檔案中找不到工作表');students=rowsToRoster(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:'',raw:false}))}else throw new Error('不支援此檔案格式');await acceptRoster(students,file.name)}catch(err){console.error(err);let msg='名單匯入失敗：'+err.message;if(ext==='numbers')msg+='\n若此 Numbers 檔版本無法直接解析，請在 Numbers 選「輸出／傳送副本 → Excel」後，以 .xlsx 匯入。';alert(msg)}}
  function installUI(){const badge=document.getElementById('versionBadge');if(badge)badge.textContent='v'+DEV_VERSION;const page=document.getElementById('p-roster');if(!page)return;const firstCard=page.querySelector('.card');const note=firstCard?.querySelector('.muted');if(note)note.textContent='學生名單至少包含「學號、姓名」。可直接匯入 CSV、XLSX、XLS、Apple Numbers，或從試算表複製兩欄後貼上。';const textarea=document.getElementById('rosterText');if(!textarea||document.getElementById('rosterFileImport'))return;const row=textarea.parentElement.querySelector('.row');const label=document.createElement('label');label.className='btn';label.innerHTML='匯入原始名單檔 <input id="rosterFileImport" type="file" accept="'+SUPPORTED+'" hidden>';row.insertBefore(label,row.firstChild);const hint=document.createElement('span');hint.className='muted';hint.textContent='CSV / XLSX / XLS / Numbers';row.insertBefore(hint,label.nextSibling);document.getElementById('rosterFileImport').addEventListener('change',async e=>{await importFile(e.target.files?.[0]);e.target.value=''})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(installUI,0));else setTimeout(installUI,0);
})();
